// Code generated by go-bindata. DO NOT EDIT.
// sources:
// data/fonts/default.ttf
// data/icons/icon_32.png
// data/icons/icon_64.png
// data/models/crate/crate.mtl
// data/models/crate/crate.obj
// data/models/crate/crate.png
// data/models/cube.fbx
// data/models/cube.mtl
// data/models/cube.obj
// data/models/monkey.fbx
// data/models/plane.fbx
// data/models/plane.mtl
// data/models/plane.obj
// data/models/teapot.fbx
// data/models/teapot.mtl
// data/models/teapot.obj
// data/models/teapot.png
// data/music/bgm.mp3
// data/ui/menubar.png
// +build !release


package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// bindataDataFontsDefaultttf reads file data from disk. It returns an error on failure.
func bindataDataFontsDefaultttf() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/fonts/default.ttf"
	name := "data/fonts/default.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataIconsIcon32png reads file data from disk. It returns an error on failure.
func bindataDataIconsIcon32png() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/icons/icon_32.png"
	name := "data/icons/icon_32.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataIconsIcon64png reads file data from disk. It returns an error on failure.
func bindataDataIconsIcon64png() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/icons/icon_64.png"
	name := "data/icons/icon_64.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCrateCratemtl reads file data from disk. It returns an error on failure.
func bindataDataModelsCrateCratemtl() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/crate/crate.mtl"
	name := "data/models/crate/crate.mtl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCrateCrateobj reads file data from disk. It returns an error on failure.
func bindataDataModelsCrateCrateobj() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/crate/crate.obj"
	name := "data/models/crate/crate.obj"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCrateCratepng reads file data from disk. It returns an error on failure.
func bindataDataModelsCrateCratepng() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/crate/crate.png"
	name := "data/models/crate/crate.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCubefbx reads file data from disk. It returns an error on failure.
func bindataDataModelsCubefbx() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/cube.fbx"
	name := "data/models/cube.fbx"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCubemtl reads file data from disk. It returns an error on failure.
func bindataDataModelsCubemtl() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/cube.mtl"
	name := "data/models/cube.mtl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsCubeobj reads file data from disk. It returns an error on failure.
func bindataDataModelsCubeobj() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/cube.obj"
	name := "data/models/cube.obj"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsMonkeyfbx reads file data from disk. It returns an error on failure.
func bindataDataModelsMonkeyfbx() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/monkey.fbx"
	name := "data/models/monkey.fbx"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsPlanefbx reads file data from disk. It returns an error on failure.
func bindataDataModelsPlanefbx() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/plane.fbx"
	name := "data/models/plane.fbx"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsPlanemtl reads file data from disk. It returns an error on failure.
func bindataDataModelsPlanemtl() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/plane.mtl"
	name := "data/models/plane.mtl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsPlaneobj reads file data from disk. It returns an error on failure.
func bindataDataModelsPlaneobj() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/plane.obj"
	name := "data/models/plane.obj"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsTeapotfbx reads file data from disk. It returns an error on failure.
func bindataDataModelsTeapotfbx() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/teapot.fbx"
	name := "data/models/teapot.fbx"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsTeapotmtl reads file data from disk. It returns an error on failure.
func bindataDataModelsTeapotmtl() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/teapot.mtl"
	name := "data/models/teapot.mtl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsTeapotobj reads file data from disk. It returns an error on failure.
func bindataDataModelsTeapotobj() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/teapot.obj"
	name := "data/models/teapot.obj"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataModelsTeapotpng reads file data from disk. It returns an error on failure.
func bindataDataModelsTeapotpng() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/models/teapot.png"
	name := "data/models/teapot.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataMusicBgmmp3 reads file data from disk. It returns an error on failure.
func bindataDataMusicBgmmp3() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/music/bgm.mp3"
	name := "data/music/bgm.mp3"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataDataUiMenubarpng reads file data from disk. It returns an error on failure.
func bindataDataUiMenubarpng() (*asset, error) {
	path := "/opt/repos/GoDusk/example/data/ui/menubar.png"
	name := "data/ui/menubar.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}


//
// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
//
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
// nolint: deadcode
//
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

//
// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or could not be loaded.
//
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// AssetNames returns the names of the assets.
// nolint: deadcode
//
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

//
// _bindata is a table, holding each asset generator, mapped to its name.
//
var _bindata = map[string]func() (*asset, error){
	"data/fonts/default.ttf":      bindataDataFontsDefaultttf,
	"data/icons/icon_32.png":      bindataDataIconsIcon32png,
	"data/icons/icon_64.png":      bindataDataIconsIcon64png,
	"data/models/crate/crate.mtl": bindataDataModelsCrateCratemtl,
	"data/models/crate/crate.obj": bindataDataModelsCrateCrateobj,
	"data/models/crate/crate.png": bindataDataModelsCrateCratepng,
	"data/models/cube.fbx":        bindataDataModelsCubefbx,
	"data/models/cube.mtl":        bindataDataModelsCubemtl,
	"data/models/cube.obj":        bindataDataModelsCubeobj,
	"data/models/monkey.fbx":      bindataDataModelsMonkeyfbx,
	"data/models/plane.fbx":       bindataDataModelsPlanefbx,
	"data/models/plane.mtl":       bindataDataModelsPlanemtl,
	"data/models/plane.obj":       bindataDataModelsPlaneobj,
	"data/models/teapot.fbx":      bindataDataModelsTeapotfbx,
	"data/models/teapot.mtl":      bindataDataModelsTeapotmtl,
	"data/models/teapot.obj":      bindataDataModelsTeapotobj,
	"data/models/teapot.png":      bindataDataModelsTeapotpng,
	"data/music/bgm.mp3":          bindataDataMusicBgmmp3,
	"data/ui/menubar.png":         bindataDataUiMenubarpng,
}

//
// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
//
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, &os.PathError{
					Op: "open",
					Path: name,
					Err: os.ErrNotExist,
				}
			}
		}
	}
	if node.Func != nil {
		return nil, &os.PathError{
			Op: "open",
			Path: name,
			Err: os.ErrNotExist,
		}
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}


type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{Func: nil, Children: map[string]*bintree{
	"data": {Func: nil, Children: map[string]*bintree{
		"fonts": {Func: nil, Children: map[string]*bintree{
			"default.ttf": {Func: bindataDataFontsDefaultttf, Children: map[string]*bintree{}},
		}},
		"icons": {Func: nil, Children: map[string]*bintree{
			"icon_32.png": {Func: bindataDataIconsIcon32png, Children: map[string]*bintree{}},
			"icon_64.png": {Func: bindataDataIconsIcon64png, Children: map[string]*bintree{}},
		}},
		"models": {Func: nil, Children: map[string]*bintree{
			"crate": {Func: nil, Children: map[string]*bintree{
				"crate.mtl": {Func: bindataDataModelsCrateCratemtl, Children: map[string]*bintree{}},
				"crate.obj": {Func: bindataDataModelsCrateCrateobj, Children: map[string]*bintree{}},
				"crate.png": {Func: bindataDataModelsCrateCratepng, Children: map[string]*bintree{}},
			}},
			"cube.fbx": {Func: bindataDataModelsCubefbx, Children: map[string]*bintree{}},
			"cube.mtl": {Func: bindataDataModelsCubemtl, Children: map[string]*bintree{}},
			"cube.obj": {Func: bindataDataModelsCubeobj, Children: map[string]*bintree{}},
			"monkey.fbx": {Func: bindataDataModelsMonkeyfbx, Children: map[string]*bintree{}},
			"plane.fbx": {Func: bindataDataModelsPlanefbx, Children: map[string]*bintree{}},
			"plane.mtl": {Func: bindataDataModelsPlanemtl, Children: map[string]*bintree{}},
			"plane.obj": {Func: bindataDataModelsPlaneobj, Children: map[string]*bintree{}},
			"teapot.fbx": {Func: bindataDataModelsTeapotfbx, Children: map[string]*bintree{}},
			"teapot.mtl": {Func: bindataDataModelsTeapotmtl, Children: map[string]*bintree{}},
			"teapot.obj": {Func: bindataDataModelsTeapotobj, Children: map[string]*bintree{}},
			"teapot.png": {Func: bindataDataModelsTeapotpng, Children: map[string]*bintree{}},
		}},
		"music": {Func: nil, Children: map[string]*bintree{
			"bgm.mp3": {Func: bindataDataMusicBgmmp3, Children: map[string]*bintree{}},
		}},
		"ui": {Func: nil, Children: map[string]*bintree{
			"menubar.png": {Func: bindataDataUiMenubarpng, Children: map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
