language: go
sudo: false

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

git:
  depth: 5

addons:
  apt:
    packages: [ 'xorg-dev', 'libglu1-mesa-dev', 'libasound2-dev' ]

env:
  - GOFLAGS='-tags debug'
  - GOFLAGS=

go:
  - "1.11"
  - master

before_install:
  - go get -u github.com/shuLhan/go-bindata/...

install:
  - true

script:
  - export GO111MODULE=on
  - go generate ./...
  - cd example
  - make
