language: go
sudo: false

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

git:
  depth: 5

addons:
  apt:
    packages: [ 'xorg-dev', 'libglu1-mesa-dev', 'libasound2-dev' ]

env:
  - CONFIG=debug
  - CONFIG=release

go:
  - "1.11"
  - master

before_install:
  - go get -u github.com/shuLhan/go-bindata/...

install:
  - true

script:
  - export GO111MODULE=on
  - go generate ./...
  - go get ./...
  - cd example
  - make
